### ISSUE TITLE
Are there pretrained Word-Aligned encoder?

### ISSUE THREAD

**Issue by Crabbit-F** [owaski/WACO#2]
Would you mind share the pretrained Word-Aligned encoder? Thanks a lot!

**Comment by owaski** [comment]
Sure! I'll try to get it uploaded by the end of day.

**Comment by Crabbit-F** [comment]
Thanks! Looking forward to your sharing！

**Comment by owaski** [comment]
Sry for the delay.

I just uploaded the pretrained checkpoints (10h, 100h, 370h, 1330h) for en-de direction. Plz check here https://www.dropbox.com/scl/fo/fj9ylr8up8x4cxidexq1p/h?rlkey=mv1reocfdxyi66paayrie07fr&dl=0

**Comment by Crabbit-F** [comment]
Thank you very much! I had download and will do some expirements.
